import { useEffect, useRef } from "react";
const VIEW_W = 1440;
const VIEW_H = 1080;
const CX = 720;
const CY = 468;
const R = 286;
const CUT = R * (16 / 201);
const RING_W = 11;
const RING_R = R - RING_W / 2;
const DOT_R = CUT * 0.9;
const WORD_Y = 902;
const WORD_TRACK = 0.42 * 62;
const PLATE = "#555c64";
const HOLE_MARGIN = 4;
const T_DOT = 0.26;
const RAY_AT = [0.3, 0.54, 0.78, 1.02];
const RAY_GROW = 0.36;
const RAY_ANGLE = [90, 135, 180, 225];
const T_RING_IN = 1.2;
const T_RING_OUT = 1.72;
const T_FLOOD_IN = 1.72;
const T_FLOOD_OUT = 2.12;
const T_RING_GONE = 1.9;
const T_PLATE_IN = 1.95;
const T_PLATE_FULL = 2.32;
const T_WORD_IN = 2.28;
const T_WORD_FULL = 2.78;
const T_FADE = 3.15;
const T_END = 3.6;
const SAFETY_MARGIN_S = 2;
const clamp01 = (v) => v < 0 ? 0 : v > 1 ? 1 : v;
const ramp = (t, a, b) => clamp01((t - a) / (b - a));
const smooth = (x) => x * x * (3 - 2 * x);
const easeOut = (x) => 1 - (1 - x) ** 3;
const mix = (a, b, k) => a + (b - a) * k;
function MoonlightIntro({ onDone }) {
  const hostRef = useRef(null);
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  useEffect(() => {
    const host = hostRef.current;
    if (!host) return;
    let disposed = false;
    let done = false;
    let raf = 0;
    let safety = 0;
    const finish = () => {
      if (done || disposed) return;
      done = true;
      if (raf) cancelAnimationFrame(raf);
      raf = 0;
      clearTimeout(safety);
      onDoneRef.current();
    };
    const NS = "http://www.w3.org/2000/svg";
    const svg = document.createElementNS(NS, "svg");
    svg.setAttribute("class", "teevy-mlintro__svg");
    svg.setAttribute("viewBox", `0 0 ${VIEW_W} ${VIEW_H}`);
    svg.setAttribute("preserveAspectRatio", "xMidYMid meet");
    const defs = document.createElementNS(NS, "defs");
    svg.appendChild(defs);
    const fullMask = (id, bg) => {
      const mask = document.createElementNS(NS, "mask");
      mask.setAttribute("id", id);
      mask.setAttribute("maskUnits", "userSpaceOnUse");
      mask.setAttribute("x", "0");
      mask.setAttribute("y", "0");
      mask.setAttribute("width", String(VIEW_W));
      mask.setAttribute("height", String(VIEW_H));
      const ground = document.createElementNS(NS, "rect");
      ground.setAttribute("width", String(VIEW_W));
      ground.setAttribute("height", String(VIEW_H));
      ground.setAttribute("fill", bg);
      mask.appendChild(ground);
      defs.appendChild(mask);
      return mask;
    };
    const diameter = (angleDeg, stroke) => {
      const line = document.createElementNS(NS, "line");
      line.setAttribute("stroke", stroke);
      line.setAttribute("stroke-width", CUT.toFixed(2));
      line.setAttribute("x1", String(CX));
      line.setAttribute("y1", String(CY));
      line.setAttribute("x2", String(CX));
      line.setAttribute("y2", String(CY));
      line.dataset.angle = String(angleDeg);
      return line;
    };
    const setLength = (line, len) => {
      const a = Number(line.dataset.angle) * Math.PI / 180;
      const dx = Math.cos(a) * len;
      const dy = Math.sin(a) * len;
      line.setAttribute("x1", (CX - dx).toFixed(2));
      line.setAttribute("y1", (CY - dy).toFixed(2));
      line.setAttribute("x2", (CX + dx).toFixed(2));
      line.setAttribute("y2", (CY + dy).toFixed(2));
    };
    const cutsMask = fullMask("ml-cuts", "#fff");
    for (const angle of RAY_ANGLE) {
      const cut = diameter(angle, "#000");
      setLength(cut, R * 1.2);
      cutsMask.appendChild(cut);
    }
    const floodHole = document.createElementNS(NS, "circle");
    floodHole.setAttribute("fill", "#000");
    floodHole.setAttribute("cx", String(CX));
    floodHole.setAttribute("cy", String(CY));
    floodHole.setAttribute("r", String(R + HOLE_MARGIN));
    cutsMask.appendChild(floodHole);
    const insideMask = fullMask("ml-inside", "#000");
    const rayWindow = document.createElementNS(NS, "circle");
    rayWindow.setAttribute("fill", "#fff");
    rayWindow.setAttribute("cx", String(CX));
    rayWindow.setAttribute("cy", String(CY));
    rayWindow.setAttribute("r", String(R + HOLE_MARGIN));
    insideMask.appendChild(rayWindow);
    const plate = document.createElementNS(NS, "rect");
    plate.setAttribute("x", String(-4 * VIEW_W));
    plate.setAttribute("y", String(-4 * VIEW_H));
    plate.setAttribute("width", String(9 * VIEW_W));
    plate.setAttribute("height", String(9 * VIEW_H));
    plate.setAttribute("fill", PLATE);
    plate.setAttribute("opacity", "0");
    svg.appendChild(plate);
    const rays = document.createElementNS(NS, "g");
    rays.setAttribute("mask", "url(#ml-inside)");
    const rayLines = RAY_ANGLE.map((angle) => {
      const ray = diameter(angle, "#fff");
      rays.appendChild(ray);
      return ray;
    });
    const dot = document.createElementNS(NS, "circle");
    dot.setAttribute("fill", "#fff");
    dot.setAttribute("cx", String(CX));
    dot.setAttribute("cy", String(CY));
    dot.setAttribute("r", "0");
    rays.appendChild(dot);
    svg.appendChild(rays);
    const disc = document.createElementNS(NS, "circle");
    disc.setAttribute("fill", "#fff");
    disc.setAttribute("cx", String(CX));
    disc.setAttribute("cy", String(CY));
    disc.setAttribute("r", String(R));
    disc.setAttribute("mask", "url(#ml-cuts)");
    svg.appendChild(disc);
    const ringLength = 2 * Math.PI * RING_R;
    const ring = document.createElementNS(NS, "circle");
    ring.setAttribute("fill", "none");
    ring.setAttribute("stroke", "#fff");
    ring.setAttribute("stroke-width", String(RING_W));
    ring.setAttribute("cx", String(CX));
    ring.setAttribute("cy", String(CY));
    ring.setAttribute("r", String(RING_R));
    ring.setAttribute("stroke-dasharray", ringLength.toFixed(2));
    ring.setAttribute("stroke-dashoffset", ringLength.toFixed(2));
    ring.setAttribute("transform", `rotate(-90 ${CX} ${CY})`);
    ring.setAttribute("opacity", "0");
    svg.appendChild(ring);
    const word = document.createElementNS(NS, "text");
    word.setAttribute("class", "teevy-mlintro__word");
    word.setAttribute("x", String(CX + WORD_TRACK / 2));
    word.setAttribute("y", String(WORD_Y));
    word.setAttribute("fill", "#fff");
    word.setAttribute("text-anchor", "middle");
    word.setAttribute("opacity", "0");
    word.textContent = "MOONLIGHT";
    svg.appendChild(word);
    host.appendChild(svg);
    const apply = (t) => {
      dot.setAttribute("r", (DOT_R * easeOut(ramp(t, 0, T_DOT))).toFixed(2));
      rayLines.forEach((ray, i) => {
        setLength(ray, R * easeOut(ramp(t, RAY_AT[i], RAY_AT[i] + RAY_GROW)));
      });
      const sweep = ramp(t, T_RING_IN, T_RING_OUT);
      ring.setAttribute("stroke-dashoffset", (ringLength * (1 - sweep ** 1.7)).toFixed(2));
      ring.setAttribute("opacity", (sweep > 0 ? 1 - ramp(t, T_FLOOD_IN, T_RING_GONE) : 0).toFixed(3));
      const close = ramp(t, T_FLOOD_IN, T_FLOOD_OUT) ** 1.35;
      const holeR = mix(R + HOLE_MARGIN, 0, close);
      floodHole.setAttribute("r", holeR.toFixed(2));
      rayWindow.setAttribute("r", holeR.toFixed(2));
      plate.setAttribute("opacity", smooth(ramp(t, T_PLATE_IN, T_PLATE_FULL)).toFixed(3));
      word.setAttribute("opacity", ramp(t, T_WORD_IN, T_WORD_FULL).toFixed(3));
      svg.style.opacity = (1 - ramp(t, T_FADE, T_END)).toFixed(3);
    };
    const start = () => {
      const t0 = performance.now();
      const tick = () => {
        const t = (performance.now() - t0) / 1e3;
        apply(Math.min(t, T_END));
        if (t >= T_END) {
          finish();
          return;
        }
        raf = requestAnimationFrame(tick);
      };
      raf = requestAnimationFrame(tick);
      safety = window.setTimeout(finish, (T_END + SAFETY_MARGIN_S) * 1e3);
    };
    apply(0);
    start();
    return () => {
      disposed = true;
      if (raf) cancelAnimationFrame(raf);
      clearTimeout(safety);
      if (svg.parentNode === host) host.removeChild(svg);
    };
  }, []);
  return <div className="teevy-mlintro" ref={hostRef} aria-hidden="true" />;
}
export {
  MoonlightIntro
};
